[package]
name = "faviconr"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Michael Borejdo <mborejdo@gmail.com>"]

[dependencies]
image = "0.23.14"
imageproc = "*"
rusttype = "0.9.2"
serde_json = "*"
colorsys = "*"
